version: '3'
services:
  php:
    container_name: php_latest
    domainname: php
    hostname: php
    build:
      context: docker/php
    working_dir: "/var/www/app"
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.222.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - internal
    links:
      - "mysql"
    volumes:
      - "./src:/var/www/app"
      - "./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf"
      - "./docker/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf"
      - "./docker/php/php.ini:/usr/local/etc/php/php.ini"
    tty: true
  nginx:
    container_name: nginx_latest
    domainname: nginx
    hostname: nginx
    image: nginx:1.13
    volumes:
      - "./src:/var/www/app"
      - "./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - ${HTTP_PORT}:80
    links:
      - "php"
    networks:
      - internal
  mysql:
    container_name: mysql
    domainname: mysql
    hostname: mysql
    image: mysql:5.6
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - "./data/mysql:/var/lib/mysql"
      - "./docker/mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
      - "./docker/mysql/mysql.conf.d/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf"
    environment:
      - "MYSQL_DATABASE=${MYSQL_DB_NAME}"
      - "MYSQL_USER=${MYSQL_DB_USER}"
      - "MYSQL_PASSWORD=${MYSQL_DB_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_DB_ROOT_PASSWORD}"
    networks:
      - internal
  phpmyadmin:
    container_name: pma
    domainname: pma
    hostname: pma
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    ports:
      - ${PMA_PORT}:80
    networks:
      - internal

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.222.0/28
